---

- hosts: all
  become: true
  pre_tasks:

    - name: Update Distribution
      tags: update
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution != "CentOS"

    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

- hosts: all
  become: true
  roles:
    - base

- hosts: dev-machines
  become: true
  roles:
    - dev-machines

- hosts: servers
  become: true
  roles:
    - servers