---

- hosts: all
  become: true
  pre_tasks:

    - name: Update Distribution
      tags: update
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: Update Distribution
      tags: update
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution != "CentOS"