- name: Add ppa deadsnakes for python 3.x
  apt_repository:
    repo: "{{ python_ppa }}"

- name: Update apt
  apt:
    update_cache: true

- name: Install Python 3.x
  apt:
    pkg: "{{ python_ver }}"

- name: Install Pycharm with option --classic
  snap:
    name: "{{ pycharm_ver }}"
    classic: true

