- name: Add ppa "deadsnakes" for python 3.x
  apt_repository:
    repo: "{{ python_ppa }}"
  apt:
    update_cache: true

- name: Install Python 3.x
  apt:
    pkg: "{{ python_ver }}"

- name: Install Pycharm with option --classic
  snap:
    name: "{{ pycharm_ver }}"
    classic: true

- name: Add Openconnect Links
  command:
    - echo "deb http://download.opensuse.org/repositories/home:/bluca:/openconnect:/release/Ubuntu_{{ ansible_distribution_version }}/ /" | sudo tee /etc/apt/sources.list.d/home:bluca:openconnect:release.list
    - curl -fsSL "https://download.opensuse.org/repositories/home:bluca:openconnect:release/Ubuntu_{{ ansible_distribution_version }}/Release.key" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/home_bluca_openconnect_release.gpg > /dev/null
  apt:
    update_cache: true

- name: Install Openconnect
  apt:
    pkg: openconnect
